GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1YjI5NWQ2NmFjNGQwMzIxMTgwMmNjNiIsImlhdCI6MTcwNjI5Mzg3NX0.fRkkE_P-qDwQPf4320CrEdfKuxAY-X87fQ4dzqecmq4

{
    "content": "Token Authentication",
    "important": true

}

###
DELETE http://localhost:3001/api/notes/655a2a883c732aed825535cf